inherit_from: ./configs/Dynamic/TUM_RGBD/tum_dynamic.yaml
scene: freiburg3_walking_rpy

data:
  input_folder: /home/zihzhu/data/Datasets/TUM/rgbd_dataset_freiburg3_walking_rpy
cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480 
  W: 640 
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6