inherit_from: ./configs/Dynamic/Wild_SLAM_Mocap/wild_slam_mocap.yaml
scene: ANYmal2

data:
  input_folder: /home/zihzhu/data/Datasets/WildSLAM/collected/ANYmal2

cam: 
  fx: 647.7445068359375
  fy: 646.9425659179688